### ISSUE TITLE
value carbratio is out of hard limits.

### ISSUE THREAD

**Issue by infallibleapex** [winemug/omnipy#18]
I am 100% SURE I am missing something here, but I can't figure out where to set my carb ratio... 

Any help would be greatly appreciated!

**Comment by Kywalh** [comment]
I don't really think it is omnipy related.
You can change your carbs ratio in Nightscout if you use it or in your local profile in AAPS.

**Comment by winemug** [comment]
Link to hard limits imposed by AAPS:
https://androidaps.readthedocs.io/en/latest/EN/Configuration/Preferences.html#patient-age
