### ISSUE TITLE
Omnipod > Diasend/Glooko

### ISSUE THREAD

**Issue by haspden** [winemug/omnipy#26]
If using Omnipy, am I right in assuming that there is no way to get the insulin delivery into Diasend/Glooko? With the PDM you can upload this device, but I assume that information is stored in the PDM, and can not be backfilled from the pod itself at a later date to be uploaded ?

Thanks

**Comment by jordan-damron** [comment]
Yes, everything you have just said is correct. The way glooko works is by getting data from pdm, so no pdm, no glooko.
