### ISSUE TITLE
suggestion: put information about how to get log files (and which ones) in the wiki support page

### ISSUE THREAD

**Issue by bionictom** [winemug/omnipy#27]
I think it'd be helpful to troubleshoot if there was a bit information about which files to upload and where to find them.

**Comment by dexdan** [comment]
I've added something but don't have a mac so aren't sure what a good SFTP client to recommend is on mac.... any suggestions? Many thanks.

**Comment by jordan-damron** [comment]
Hi, I have a Mac, I use FileZilla to get error logs from omnipy. It works great
